log_level: INFO

server_info:
    fake: true
    ip: 192.168.100.17
    port: 9000
    access_token : "ec31c154fc0cbf4ba39eb48689ebcbfaacf8067f"

gm_info:
    gm_output: "/home/henry/share/account_out"
    account1:
        acct_name: jack
        acct_id: 6a89549c-a1df-11ec-aaef-00163e0a4100
        acct_input: "/home/henry/share/jack_input1"

    account2:
        acct_name: henry
        acct_id: 1751ebfe-9ec1-11ec-ba58-00163e0a4100
        acct_input: "/home/henry/share/henry_input1"
