log_level: DEBUG
log_dir: ~/gmadaptor/logs

server_info:
    ip: 192.168.100.201
    port: 9000
    access_token : "84ae0899-7a8d-44ff-9983-4fa7cbbc424b"

gm_info:
    fake: false
    gm_output: "~/gmadaptor/FileOrders/out"
    trade_fees:
        commission: 2.5
        stamp_duty: 10.0
        transfer_fee: 0.1
        minimum_cost: 5.0
    accounts:
        - name: fileorder_s01
          acct_id: 1a66e81c-ae5d-11ec-aef5-00163e0a4100
          acct_input: "~/gmadaptor/FileOrders/inputs/fileorder_s01"
        - name: fileorder_r01
          acct_id: a751a30f-a4dd-11ec-ba99-00163e0a4100
          acct_input: "~/gmadaptor/FileOrders/inputs/fileorder_r01"
